name: CI

on: 
  push:
   branches: ["main"]

jobs:

  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci -f


#   distributed-task:
#     runs-on: ubuntu-latest
#     needs: install-deps
#     strategy:
#       matrix:
#         target: ['test', 'lint', 'build']
#         jobIndex: [1, 2, 3, 4]
#     env:
#       jobCount: 4
#     steps:
#       - uses: actions/checkout@v2
#       - name: Cache node modules
#         uses: actions/cache@v2
#         with:
#           path: node_modules
#           key: cache-node-modules-${{ hashFiles('package-lock.json') }}
#       - name: Cache Nx
#         uses: actions/cache@v2
#         with:
#           path: node_modules/.cache/nx
#           key: cache-nx-${{ hashFiles('package-lock.json') }}-${{ matrix.target }}-${{ matrix.jobIndex }}-${{ github.sha }}
#           restore-keys: |
#             cache-nx-${{ hashFiles('package-lock.json') }}-${{ matrix.target }}-${{ matrix.jobIndex }}-
#             cache-nx-${{ hashFiles('package-lock.json') }}-
#       - run: git fetch --no-tags --prune --depth=1 origin main
#       - name: nx run-many:${{ matrix.target }}
#         run: node ./tools/scripts/run-many.js ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.jobCount }} $GITHUB_REF
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: install-deps
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - run: npm run build:editor
      - name: Setup Pages
        uses: actions/configure-pages@v3.0.2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './dist/editor'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1    
        
