# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Nrwl Nx
  # You may pin to the exact commit or the version.
  # uses: MansaGroup/nrwl-nx-action@3cd1b0217bc6bec52e5f52f05fefabc8c1076a4a
        uses: MansaGroup/nrwl-nx-action@v3.2.2
        with:
          # Comma-separated list of targets to execute
          targets: build
          # Comma-separated list of projects to use
          projects: editor
          # Run the targets on all projects
          all: false
          # Use the Nx' affected subcommand to only process affected projects
          affected: false
          # Number of tasks to execute in parallel (can be expensive)
          parallel: 1
          # Optional arguments to append to the Nx command
          # args: # optional, default is 
          # Enable support for Nx Cloud
          nxCloud: false
          # Path to the Nx workspace, needed if not the repository root
          # workingDirectory: # optional
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './dist/editor'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
